/************************************************************************************************************
 * @version 6.5.0.370 @ 2026-08-10
 * @copyright 2002-2026 Melbis
 * @link https://melbis.com
 * @author Dmytro Kasianov
 ************************************************************************************************************/


INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('95', 'code 95', '0', '0', '0', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('24', 'TOPIC_ALT_KIND_KEY', '95', '1', '1', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('22', 'code 22', '95', '1', '2', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('19', 'TOPIC_KIND_KEY', '22', '2', '3', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('11', 'TOPIC_TEMPL_KEY', '22', '2', '4', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('21', 'TOPIC_ORDER_KEY', '22', '2', '5', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('12', 'FILES_TOPIC', '22', '2', '6', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('43', 'code 43', '95', '1', '7', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('44', 'STORE_KIND_KEY', '43', '2', '8', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('45', 'STORE_STATUS_KEY', '43', '2', '9', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('98', 'STORE_STATE_KEY', '43', '2', '10', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('46', 'STORE_TEMPL_KEY', '43', '2', '11', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('47', 'FILES_STORE', '43', '2', '12', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('62', 'code 62', '43', '2', '13', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('140', 'STORE_SET_OBJ_KEY', '62', '3', '14', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('49', 'STORE_SET_KIND_KEY', '62', '3', '15', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('1', 'code 1', '0', '0', '16', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('137', 'code 137', '1', '1', '17', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('138', 'PROVIDER_KIND_KEY', '137', '2', '18', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('139', 'PROVIDER_STATE_KEY', '137', '2', '19', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('108', 'code 108', '1', '1', '20', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('109', 'BRAND_KIND_KEY', '108', '2', '21', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('110', 'FILES_BRAND', '108', '2', '22', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('32', 'code 32', '1', '1', '23', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('33', 'code 33', '32', '2', '24', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('2', 'INFO_KIND_KEY', '33', '3', '25', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('97', 'INFO_TYPE_KEY', '33', '3', '26', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('4', 'FILES_INFO', '33', '3', '27', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('34', 'code 34', '32', '2', '28', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('52', 'INFO_VALUE_KIND_KEY', '34', '3', '29', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('5', 'FILES_INFO_VALUE', '34', '3', '30', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('92', 'code 92', '1', '1', '31', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('93', 'PARAM_KIND_KEY', '92', '2', '32', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('50', 'code 50', '1', '1', '33', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('51', 'DISC_KIND_KEY', '50', '2', '34', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('94', 'code 94', '0', '0', '35', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('91', 'code 91', '94', '1', '36', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('69', 'TOPIC_FILTER_KIND_KEY', '91', '2', '37', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('142', 'code 142', '94', '1', '38', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('143', 'code 143', '142', '2', '39', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('144', 'LANG_KIND_KEY', '143', '3', '40', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('152', 'FILES_LANG', '143', '3', '41', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('145', 'code 145', '142', '2', '42', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('146', 'TRANS_KIND_KEY', '145', '3', '43', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('149', 'TRANS_TABLE_KEY', '145', '3', '44', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('147', 'code 147', '142', '2', '45', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('148', 'TRANS_ORIGIN_KIND_KEY', '147', '3', '46', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('54', 'code 54', '94', '1', '47', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('55', 'ADVERT_KIND_KEY', '54', '2', '48', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('57', 'code 57', '54', '2', '49', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('56', 'ADVERT_TEXT_KIND_KEY', '57', '3', '50', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('58', 'FILES_ADVERT_TEXT', '57', '3', '51', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('101', 'code 101', '54', '2', '52', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('60', 'ADVERT_GOODS_KIND_KEY', '101', '3', '53', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('102', 'code 102', '54', '2', '54', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('103', 'ADVERT_LINK_OBJ_KEY', '102', '3', '55', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('61', 'ADVERT_LINK_KIND_KEY', '102', '3', '56', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('127', 'code 127', '94', '1', '57', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('128', 'TASK_KIND_KEY', '127', '2', '58', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('129', 'TASK_STATE_KEY', '127', '2', '59', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('130', 'code 130', '94', '1', '60', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('131', 'code 131', '130', '2', '61', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('133', 'WEB_KEY_KIND_KEY', '131', '3', '62', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('134', 'FILES_WEB_KEY', '131', '3', '63', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('132', 'code 132', '130', '2', '64', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('135', 'WEB_KEY_VALUE_KIND_KEY', '132', '3', '65', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('136', 'FILES_WEB_KEY_VALUE', '132', '3', '66', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('70', 'code 70', '0', '0', '67', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('71', 'code 71', '70', '1', '68', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('72', 'code 72', '71', '2', '69', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('86', 'code 86', '72', '3', '70', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('73', 'FIELD_KIND_KEY', '86', '4', '71', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('74', 'FIELD_SPEC_KEY', '86', '4', '72', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('153', 'FILES_FIELD', '86', '4', '73', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('87', 'code 87', '72', '3', '74', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('75', 'FIELD_VALUE_KIND_KEY', '87', '4', '75', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('76', 'code 76', '70', '1', '76', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('111', 'code 111', '76', '2', '77', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('112', 'code 112', '111', '3', '78', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('113', 'ORDER_STORE_OPTION_KIND_KEY', '112', '4', '79', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('88', 'code 88', '76', '2', '80', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('77', 'code 77', '88', '3', '81', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('78', 'ORDER_OPTION_KIND_KEY', '77', '4', '82', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('154', 'FILES_ORDER_OPTION', '77', '4', '83', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('84', 'code 84', '88', '3', '84', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('79', 'ORDER_OPTION_VALUE_KIND_KEY', '84', '4', '85', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('155', 'FILES_ORDER_OPTION_VALUE', '84', '4', '86', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('106', 'code 106', '0', '0', '87', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('80', 'code 80', '106', '1', '88', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('81', 'MODULE_ORDER_VERSION_CALC', '80', '2', '89', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('83', 'MODULE_ORDER_VERSION_ADD', '80', '2', '90', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('107', 'ORDER_TRANSPORT', '80', '2', '91', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('118', 'code 118', '106', '1', '92', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('116', 'MODULE_NOTIFICATION', '118', '2', '93', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('117', 'EVENT_NOTIFICATION', '118', '2', '94', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('150', 'code 150', '106', '1', '95', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('151', 'MODULE_TRANSLATE_LINE', '150', '2', '96', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('8', 'FILES_KEY_VALUE', '0', '0', '97', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('66', 'code 66', '8', '1', '98', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('9', 'FILES_PROFILE', '66', '2', '99', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('7', 'FILES_MASK', '66', '2', '100', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('67', 'code 67', '8', '1', '101', '1');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('65', 'HTML_OPTION', '67', '2', '102', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('123', 'HTML_TAG', '67', '2', '103', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('124', 'HTML_CLASS', '67', '2', '104', '0');
INSERT INTO {DBNICK}_key (id, code, tindex, tlevel, absindex, folder) VALUES ('125', 'HTML_TEMPLATE', '67', '2', '105', '0');
UPDATE {DBNICK}_generator SET gen_value = 155 WHERE table_name = 'key';

INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('1', 'INFO_KIND_KEY', 'kDefault', '1', '1');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('3', 'FILES_INFO', 'kBase', '1', '1');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('4', 'FILES_INFO_VALUE', 'kBase', '1', '1');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('5', 'FILES_INFO', 'kDefault', '0', '4');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('7', 'FILES_INFO_VALUE', 'kDefault', '0', '4');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('10', 'FILES_INFO', 'kDescr', '1', '3');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('11', 'FILES_INFO_VALUE', 'kDescr', '1', '3');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('15', 'FILES_KEY_VALUE', 'kBase', '1', '1');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('16', 'FILES_MASK', 'Без маски', '1', '1');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('17', 'FILES_PROFILE', 'Пример', '0', '1');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('20', 'TOPIC_TEMPL_KEY', 'kDefault', '1', '1');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('22', 'FILES_TOPIC', 'kBase', '1', '1');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('24', 'FILES_TOPIC', 'kDescr', '1', '3');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('25', 'FILES_TOPIC', 'kDefault', '0', '4');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('35', 'TOPIC_KIND_KEY', 'kGoods', '1', '2');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('37', 'TOPIC_KIND_KEY', 'kLink', '1', '4');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('39', 'TOPIC_ORDER_KEY', 'kDefault', '1', '1');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('40', 'TOPIC_ALT_KIND_KEY', 'kTree', '1', '1');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('41', 'TOPIC_ALT_KIND_KEY', 'kCenter', '0', '2');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('70', 'STORE_KIND_KEY', 'kDefault', '1', '70');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('71', 'STORE_TEMPL_KEY', 'kDefault', '1', '71');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('72', 'STORE_STATUS_KEY', 'kExist', '1', '72');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('73', 'STORE_STATUS_KEY', 'kAbsent', '1', '73');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('74', 'STORE_STATUS_KEY', 'kExistOrder', '0', '74');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('75', 'STORE_STATUS_KEY', 'kAbsentOrder', '0', '75');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('76', 'FILES_STORE', 'kBase', '1', '76');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('78', 'FILES_STORE', 'kDescr', '1', '78');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('79', 'FILES_STORE', 'kDefault', '0', '79');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('80', 'FILES_STORE', 'kDescrImg', '0', '80');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('82', 'STORE_SET_KIND_KEY', 'kDefault', '1', '82');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('83', 'DISC_KIND_KEY', 'kOrder', '1', '83');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('85', 'DISC_KIND_KEY', 'kBalanceSum', '0', '85');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('86', 'INFO_VALUE_KIND_KEY', 'kDefault', '1', '86');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('94', 'ADVERT_KIND_KEY', 'kDefault', '1', '94');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('100', 'ADVERT_TEXT_KIND_KEY', 'kDefault', '1', '100');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('101', 'FILES_ADVERT_TEXT', 'kBase', '1', '101');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('103', 'FILES_ADVERT_TEXT', 'kDescr', '1', '103');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('104', 'FILES_ADVERT_TEXT', 'kDefault', '0', '104');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('105', 'ADVERT_GOODS_KIND_KEY', 'kDefault', '1', '105');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('107', 'ADVERT_LINK_KIND_KEY', 'kId', '1', '107');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('110', 'HTML_OPTION', 'kCSS', '1', '110');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('114', 'TOPIC_FILTER_KIND_KEY', 'kDefault', '1', '114');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('115', 'FIELD_KIND_KEY', 'kDefault', '1', '115');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('116', 'FIELD_SPEC_KEY', 'kDefault', '1', '116');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('117', 'FIELD_VALUE_KIND_KEY', 'kDefault', '1', '117');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('120', 'ORDER_OPTION_KIND_KEY', 'kDefault', '1', '120');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('121', 'ORDER_OPTION_VALUE_KIND_KEY', 'kDefault', '1', '121');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('123', 'MODULE_ORDER_VERSION_CALC', 'melbis_inc_logic.php', '0', '123');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('125', 'MODULE_ORDER_VERSION_ADD', 'melbis_inc_logic.php', '0', '125');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('131', 'PARAM_KIND_KEY', 'kDefault', '1', '131');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('135', 'INFO_TYPE_KEY', 'kSet', '1', '135');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('137', 'INFO_TYPE_KEY', 'kDecimal', '1', '137');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('138', 'STORE_STATE_KEY', 'kDefault', '1', '138');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('145', 'STORE_STATE_KEY', 'kImport', '0', '145');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('146', 'STORE_STATE_KEY', 'kDescrNeed', '0', '146');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('147', 'STORE_STATE_KEY', 'kDescrUp', '0', '147');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('148', 'STORE_STATE_KEY', 'kOk', '0', '148');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('149', 'ADVERT_LINK_OBJ_KEY', 'kTopic', '1', '149');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('150', 'ADVERT_LINK_OBJ_KEY', 'kGoods', '1', '150');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('153', 'ORDER_TRANSPORT', 'kDefault', '1', '153');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('154', 'BRAND_KIND_KEY', 'kDefault', '1', '154');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('155', 'FILES_BRAND', 'kBase', '1', '155');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('156', 'FILES_BRAND', 'kDescr', '1', '156');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('157', 'FILES_BRAND', 'kDefault', '0', '157');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('159', 'ORDER_STORE_OPTION_KIND_KEY', 'kDefault', '1', '159');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('161', 'MODULE_NOTIFICATION', 'melbis_inc_logic.php', '0', '161');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('163', 'EVENT_NOTIFICATION', 'kNewOrder', '0', '163');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('164', 'EVENT_NOTIFICATION', 'kNewClient', '0', '164');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('178', 'FILES_KEY_VALUE', 'kAttach', '1', '178');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('181', 'HTML_TAG', 'p', '1', '1');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('182', 'HTML_TAG', 'div', '1', '3');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('183', 'HTML_TAG', 'span', '1', '2');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('184', 'HTML_TAG', 'h1', '1', '5');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('191', 'HTML_TAG', 'h2', '1', '6');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('192', 'HTML_TAG', 'h3', '1', '7');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('193', 'HTML_TAG', 'h4', '1', '8');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('194', 'HTML_TAG', 'h5', '1', '9');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('195', 'HTML_TAG', 'h6', '1', '10');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('196', 'HTML_TAG', 'a', '1', '4');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('253', 'HTML_TEMPLATE', 'Table', '0', '253');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('257', 'HTML_OPTION', 'kContainer', '1', '257');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('261', 'TASK_KIND_KEY', 'kDefault', '1', '261');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('262', 'TASK_KIND_KEY', 'kUrgent', '1', '262');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('263', 'TASK_KIND_KEY', 'kWish', '1', '263');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('264', 'TASK_KIND_KEY', 'kPriority1', '0', '264');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('265', 'TASK_KIND_KEY', 'kPriority2', '0', '265');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('266', 'TASK_KIND_KEY', 'kPriority3', '0', '266');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('267', 'TASK_STATE_KEY', 'kNew', '1', '267');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('268', 'TASK_STATE_KEY', 'kAccept', '1', '268');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('269', 'TASK_STATE_KEY', 'kHold', '1', '269');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('270', 'TASK_STATE_KEY', 'kDone', '1', '270');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('271', 'TASK_STATE_KEY', 'kStop', '1', '271');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('272', 'TASK_STATE_KEY', 'kTrans', '1', '272');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('273', 'TASK_STATE_KEY', 'kExplain', '1', '273');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('274', 'TASK_STATE_KEY', 'kComment', '1', '274');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('275', 'TASK_STATE_KEY', 'kClose', '1', '275');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('277', 'WEB_KEY_KIND_KEY', 'kDefault', '1', '277');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('278', 'WEB_KEY_VALUE_KIND_KEY', 'kDefault', '1', '278');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('279', 'FILES_WEB_KEY', 'kBase', '1', '279');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('280', 'FILES_WEB_KEY', 'kDescr', '1', '280');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('281', 'FILES_WEB_KEY', 'kDefault', '0', '281');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('282', 'FILES_WEB_KEY_VALUE', 'kBase', '1', '282');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('283', 'FILES_WEB_KEY_VALUE', 'kDescr', '1', '283');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('284', 'FILES_WEB_KEY_VALUE', 'kDefault', '0', '284');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('286', 'PROVIDER_KIND_KEY', 'kDefault', '1', '286');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('287', 'PROVIDER_STATE_KEY', 'kDefault', '1', '287');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('288', 'INFO_TYPE_KEY', 'kText', '1', '288');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('289', 'STORE_SET_OBJ_KEY', 'kGoods', '1', '289');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('290', 'STORE_SET_OBJ_KEY', 'kTopic', '1', '290');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('291', 'HTML_OPTION', 'kPostProcess', '1', '291');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('292', 'LANG_KIND_KEY', 'kDefault', '1', '292');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('293', 'TRANS_KIND_KEY', 'kDefault', '1', '293');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('294', 'TRANS_ORIGIN_KIND_KEY', 'kDefault', '1', '294');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('295', 'TRANS_TABLE_KEY', 'kDefault', '1', '295');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('296', 'TRANS_TABLE_KEY', 'kTopic', '0', '296');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('297', 'TRANS_TABLE_KEY', 'kStore', '0', '297');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('298', 'TRANS_TABLE_KEY', 'kTag', '0', '298');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('299', 'MODULE_TRANSLATE_LINE', 'melbis_inc_lang.php', '0', '299');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('300', 'HTML_TAG', 'blockquote', '1', '300');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('301', 'HTML_TAG', 'code', '1', '301');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('302', 'HTML_TAG', 'small', '1', '302');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('303', 'HTML_TAG', 'mark', '1', '303');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('304', 'HTML_TAG', 'sub', '1', '304');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('305', 'HTML_TAG', 'sup', '1', '305');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('306', 'HTML_TAG', 'pre', '1', '306');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('307', 'HTML_TEMPLATE', 'YouTube', '0', '307');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('308', 'HTML_TAG', 'iframe', '1', '308');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('309', 'FILES_LANG', 'kBase', '1', '309');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('310', 'FILES_LANG', 'kDescr', '1', '310');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('311', 'FILES_LANG', 'kDefault', '0', '311');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('313', 'FILES_FIELD', 'kBase', '1', '313');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('314', 'FILES_FIELD', 'kDescr', '1', '314');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('315', 'FILES_FIELD', 'kDefault', '0', '315');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('316', 'FILES_ORDER_OPTION', 'kBase', '0', '316');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('317', 'FILES_ORDER_OPTION', 'kDescr', '0', '317');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('318', 'FILES_ORDER_OPTION', 'kDefault', '0', '318');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('319', 'FILES_ORDER_OPTION_VALUE', 'kBase', '1', '319');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('320', 'FILES_ORDER_OPTION_VALUE', 'kDescr', '1', '320');
INSERT INTO {DBNICK}_key_value (id, key_code, key_name, sys_key, pos) VALUES ('321', 'FILES_ORDER_OPTION_VALUE', 'kDefault', '0', '321');
UPDATE {DBNICK}_generator SET gen_value = 321 WHERE table_name = 'key_value';
